spring:
  datasource:
    url: jdbc:mysql://localhost:3306/develhope
    username: develhope
    password: g&zr62LweWsj28
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true
